apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp
  labels:
    app: postgres-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-mcp
  template:
    metadata:
      labels:
        app: postgres-mcp
    spec:
      containers:
        - name: postgres-mcp
          image: vetc/mcp:latest
          imagePullPolicy: IfNotPresent
          command: ["python"]
          args: ["src/mcp_server/postgres_server.py"]
          envFrom:
            - secretRef:
                name: mcp-env
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-mcp
spec:
  selector:
    app: postgres-mcp
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP

